version: '3'
services:
  train:
    image: rudrapalakiran55/paytmstrain:latest
    port:
      - "80:80"
    replicas: 3

  dth:
    image: rudrapalakiran55/paytmsdth:latest
    port:
      - "81:80"
    replicas: 3

  movies:
    image: rudrapalakiran55/paytmsmovies:latest
    port:
      - "82:80"
    replicas: 3

